### ISSUE TITLE
Localisation : We should have localised application.

### ISSUE THREAD

**Issue by PankajMean** [PankajMean/MeanCrud#6]
Guys, We need to have localisation in our application.
So you can suggest the way that we can achieve it, Thanks.

**Comment by naitik211** [comment]
@PankajMean , Yes. This will be great if we do it simultaneously. Can we use one of these two ?

Please have a look towards this:
1. http://angular-translate.github.io/
2. http://dailyjs.com/2014/04/08/angular-localize/
